In [1]:
import numpy as np

# Создаем массив NumPy размером 3x3 с числами от 1 до 9
arr = np.arange(1, 10).reshape((3, 3))
print("Исходный массив:\n", arr)

# Умножаем все элементы массива на 2
arr = arr * 2
print("\nМассив, умноженный на 2:\n", arr)

# Заменяем все элементы больше 10 на 0
arr[arr > 10] = 0
print("\nМассив с элементами больше 10 замененными на 0:\n", arr)


Исходный массив:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Массив, умноженный на 2:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Массив с элементами больше 10 замененными на 0:
 [[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


In [2]:
import numpy as np

# Создаем массив NumPy из 20 случайных целых чисел от 1 до 100
arr = np.random.randint(1, 101, 20)
print("Исходный массив:\n", arr)

# Находим и выводим все элементы, которые делятся на 5 без остатка
divisible_by_5 = arr[arr % 5 == 0]
print("\nЭлементы, делящиеся на 5 без остатка:\n", divisible_by_5)

# Заменяем элементы, делящиеся на 5, на -1
arr[arr % 5 == 0] = -1
print("\nОбновленный массив:\n", arr)


Исходный массив:
 [ 44  35  38  79  88  25  63  43  66  44  10  89  21  55  56  25  43 100
   7  96]

Элементы, делящиеся на 5 без остатка:
 [ 35  25  10  55  25 100]

Обновленный массив:
 [44 -1 38 79 88 -1 63 43 66 44 -1 89 21 -1 56 -1 43 -1  7 96]


In [3]:
import numpy as np

# Создаем два массива NumPy размером 1x5 со случайными числами от 0 до 50
arr1 = np.random.randint(0, 51, (1, 5))
arr2 = np.random.randint(0, 51, (1, 5))

print("Массив 1:\n", arr1)
print("\nМассив 2:\n", arr2)

# Объединяем массивы в один двумерный массив (по строкам)
combined_arr = np.concatenate((arr1, arr2), axis=0)
print("\nОбъединенный массив:\n", combined_arr)

# Разделяем полученный массив на два массива, каждый из которых содержит 5 элементов
arr_split = np.split(combined_arr, 2)
print("\nРазделенный массив 1:\n", arr_split[0])
print("\nРазделенный массив 2:\n", arr_split[1])


Массив 1:
 [[ 6 50 30  9 42]]

Массив 2:
 [[25  5 36  0 10]]

Объединенный массив:
 [[ 6 50 30  9 42]
 [25  5 36  0 10]]

Разделенный массив 1:
 [[ 6 50 30  9 42]]

Разделенный массив 2:
 [[25  5 36  0 10]]


In [4]:
import numpy as np

# Создаем массив из 50 чисел, равномерно распределенных от -10 до 10
arr = np.linspace(-10, 10, 50)

print("Исходный массив:\n", arr)

# Вычисляем сумму всех элементов
total_sum = np.sum(arr)
print("\nСумма всех элементов:", total_sum)

# Вычисляем сумму положительных элементов
positive_elements = arr[arr > 0]  # Выбираем положительные элементы
positive_sum = np.sum(positive_elements)
print("\nСумма положительных элементов:", positive_sum)

# Вычисляем сумму отрицательных элементов
negative_elements = arr[arr < 0]  # Выбираем отрицательные элементы
negative_sum = np.sum(negative_elements)
print("\nСумма отрицательных элементов:", negative_sum)



Исходный массив:
 [-10.          -9.59183673  -9.18367347  -8.7755102   -8.36734694
  -7.95918367  -7.55102041  -7.14285714  -6.73469388  -6.32653061
  -5.91836735  -5.51020408  -5.10204082  -4.69387755  -4.28571429
  -3.87755102  -3.46938776  -3.06122449  -2.65306122  -2.24489796
  -1.83673469  -1.42857143  -1.02040816  -0.6122449   -0.20408163
   0.20408163   0.6122449    1.02040816   1.42857143   1.83673469
   2.24489796   2.65306122   3.06122449   3.46938776   3.87755102
   4.28571429   4.69387755   5.10204082   5.51020408   5.91836735
   6.32653061   6.73469388   7.14285714   7.55102041   7.95918367
   8.36734694   8.7755102    9.18367347   9.59183673  10.        ]

Сумма всех элементов: 7.105427357601002e-15

Сумма положительных элементов: 127.55102040816328

Сумма отрицательных элементов: -127.55102040816327


In [5]:
import numpy as np

# Создаем единичную матрицу размером 4x4
identity_matrix = np.eye(4)
print("Единичная матрица:\n", identity_matrix)

# Создаем диагональную матрицу размером 4x4 с диагональными элементами [5, 10, 15, 20]
diagonal_elements = [5, 10, 15, 20]
diagonal_matrix = np.diag(diagonal_elements)
print("\nДиагональная матрица:\n", diagonal_matrix)


Единичная матрица:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Диагональная матрица:
 [[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]


In [6]:
import numpy as np

# Создаем две квадратные матрицы NumPy размером 3x3 со случайными целыми числами от 1 до 20
matrix1 = np.random.randint(1, 21, (3, 3))
matrix2 = np.random.randint(1, 21, (3, 3))

print("Матрица 1:\n", matrix1)
print("\nМатрица 2:\n", matrix2)

# Вычисляем их сумму
sum_matrix = matrix1 + matrix2
print("\nСумма матриц:\n", sum_matrix)

# Вычисляем их разность
difference_matrix = matrix1 - matrix2
print("\nРазность матриц:\n", difference_matrix)

# Вычисляем их поэлементное произведение
elementwise_product_matrix = matrix1 * matrix2
print("\nПоэлементное произведение матриц:\n", elementwise_product_matrix)


Матрица 1:
 [[ 9  6  7]
 [ 6  6 12]
 [10 16 17]]

Матрица 2:
 [[11 16  6]
 [ 1  9 17]
 [ 7 17  1]]

Сумма матриц:
 [[20 22 13]
 [ 7 15 29]
 [17 33 18]]

Разность матриц:
 [[ -2 -10   1]
 [  5  -3  -5]
 [  3  -1  16]]

Поэлементное произведение матриц:
 [[ 99  96  42]
 [  6  54 204]
 [ 70 272  17]]


In [9]:
import numpy as np

# Создаем две матрицы:
matrix1 = np.random.randint(1, 11, (2, 3))  # 2x3
matrix2 = np.random.randint(1, 11, (3, 2))  # 3x2

print("Матрица 1 (2x3):\n", matrix1)
print("\nМатрица 2 (3x2):\n", matrix2)

# Выполняем матричное умножение с использованием оператора @
product_matrix_at = matrix1 @ matrix2

# Выполняем матричное умножение с использованием np.dot()
product_matrix_dot = np.dot(matrix1, matrix2)


print("\nМатричное умножение (оператор @):\n", product_matrix_at)
print("\nМатричное умножение (np.dot()):\n", product_matrix_dot)


Матрица 1 (2x3):
 [[10  8  4]
 [ 6  5  8]]

Матрица 2 (3x2):
 [[ 1  9]
 [ 7 10]
 [ 2  8]]

Матричное умножение (оператор @):
 [[ 74 202]
 [ 57 168]]

Матричное умножение (np.dot()):
 [[ 74 202]
 [ 57 168]]


In [10]:
import numpy as np

# Создаем случайную квадратную матрицу 3x3
matrix = np.random.rand(3, 3)
print("Исходная матрица:\n", matrix)

# Вычисляем определитель матрицы
determinant = np.linalg.det(matrix)
print("\nОпределитель матрицы:", determinant)

# Находим обратную матрицу (если определитель не равен нулю)
if np.abs(determinant) > 1e-8:  # Проверка на вырожденность (определитель близок к нулю)
    inverse_matrix = np.linalg.inv(matrix)
    print("\nОбратная матрица:\n", inverse_matrix)
else:
    print("\nМатрица вырождена (определитель близок к нулю), обратная матрица не существует.")


Исходная матрица:
 [[0.70936219 0.59086183 0.58919872]
 [0.78317785 0.87717868 0.64133221]
 [0.91867446 0.73783486 0.46080219]]

Определитель матрицы: -0.048383635643466746

Обратная матрица:
 [[ 1.42592428 -3.35776603  2.85000976]
 [-4.71823691  4.43137777 -0.13456128]
 [ 4.71204238 -0.40132423 -3.29631072]]


In [11]:
import numpy as np

# Создаем матрицу NumPy размером 4x4, содержащую случайные целые числа от 1 до 50
matrix = np.random.randint(1, 51, (4, 4))

print("Исходная матрица:\n", matrix)

# Находим транспонированную матрицу
transposed_matrix = matrix.T  # Или np.transpose(matrix)
print("\nТранспонированная матрица:\n", transposed_matrix)

# Находим след матрицы (сумму элементов на главной диагонали)
trace = np.trace(matrix)
print("\nСлед матрицы:", trace)


Исходная матрица:
 [[26 37 47 17]
 [48 24 32 31]
 [26 49  9  8]
 [15 39 48 44]]

Транспонированная матрица:
 [[26 48 26 15]
 [37 24 49 39]
 [47 32  9 48]
 [17 31  8 44]]

След матрицы: 103


In [12]:
import numpy as np

# Матрица коэффициентов A
A = np.array([[2, 3, -1],
              [4, -1, 2],
              [-3, 5, 4]])

# Вектор правой части B
B = np.array([5, 6, -2])

# Решение системы уравнений с помощью np.linalg.solve
x = np.linalg.solve(A, B)

# Вывод результата
print("Решение системы уравнений:\n", x)


Решение системы уравнений:
 [1.63963964 0.57657658 0.00900901]


In [15]:
import numpy as np

# Матрица коэффициентов A
A = np.array([[1, 1, 1],
              [1, -2, 0],
              [0, -1, 1]])

# Вектор правой части B
B = np.array([1000000, 0, 200000])

# Вычисление определителя матрицы A
det_A = np.linalg.det(A)

if abs(det_A) < 1e-8:
    print("Система не имеет единственного решения (определитель равен 0).")
else:
    # Вычисление определителей для x, y, z
    A_x = np.copy(A)
    A_x[:, 0] = B
    det_A_x = np.linalg.det(A_x)

    A_y = np.copy(A)
    A_y[:, 1] = B
    det_A_y = np.linalg.det(A_y)

    A_z = np.copy(A)
    A_z[:, 2] = B
    det_A_z = np.linalg.det(A_z)

    # Вычисление значений x, y, z
    x = det_A_x / det_A
    y = det_A_y / det_A
    z = det_A_z / det_A

    print("Решение методом Крамера:")
    print("x =", x)
    print("y =", y)
    print("z =", z)



Решение методом Крамера:
x = 399999.99999999953
y = 200000.0000000001
z = 399999.99999999953


In [17]:
import numpy as np

# Матрица коэффициентов A (как в методе Крамера)
A = np.array([[1, 1, 1],
              [1, -2, 0],
              [0, -1, 1]])

# Вектор правой части B (как в методе Крамера)
B = np.array([1000000, 0, 200000])

# Нахождение обратной матрицы A^-1
try:
    A_inv = np.linalg.inv(A)
    # Решение системы уравнений: x = A^-1 * B
    x = np.dot(A_inv, B)

    print("\nРешение матричным методом:")
    print("x =", x[0])
    print("y =", x[1])
    print("z =", x[2])

except np.linalg.LinAlgError:
    print("\nМатрица A не имеет обратной (вырожденная), матричный метод не применим.")




Решение матричным методом:
x = 400000.0
y = 200000.0
z = 400000.0


In [18]:
import numpy as np

# Матрица коэффициентов A (как в методе Крамера и матричном методе)
A = np.array([[1, 1, 1],
              [1, -2, 0],
              [0, -1, 1]])

# Вектор правой части B (как в методе Крамера и матричном методе)
B = np.array([1000000, 0, 200000])

# Решение с использованием np.linalg.solve
x = np.linalg.solve(A, B)

print("\nРешение с использованием np.linalg.solve:")
print("x =", x[0])
print("y =", x[1])
print("z =", x[2])




Решение с использованием np.linalg.solve:
x = 400000.0
y = 200000.0
z = 400000.00000000006


In [1]:
import numpy as np

# Матрица коэффициентов
A = np.array([[1, 1, 1],
              [1, -2, 0],
              [0, -1, 1]])

# Вектор свободных членов
b = np.array([1000000, 0, 200000])

# 3. Решение с помощью np.linalg.solve
x_solve = np.linalg.solve(A, b)
print("Решение с помощью np.linalg.solve:")
print("Первый проект:", x_solve[0], "рублей")
print("Второй проект:", x_solve[1], "рублей")
print("Третий проект:", x_solve[2], "рублей")
print("-" * 30)


# Метод Крамера
def cramer(A, b):
    det_A = np.linalg.det(A)
    if det_A == 0:
        return "Система не имеет решений или имеет бесконечно много решений"
    
    n = len(b)
    x = np.zeros(n)
    for i in range(n):
        A_i = A.copy()
        A_i[:, i] = b
        x[i] = np.linalg.det(A_i) / det_A
    return x

x_cramer = cramer(A, b)

print("Решение методом Крамера:")
print("Первый проект:", x_cramer[0], "рублей")
print("Второй проект:", x_cramer[1], "рублей")
print("Третий проект:", x_cramer[2], "рублей")
print("-" * 30)


# Матричный метод
def matrix_method(A, b):
    try:
        A_inv = np.linalg.inv(A)
        x = A_inv @ b
        return x
    except np.linalg.LinAlgError:
        return "Матрица необратима, система не имеет единственного решения."
x_matrix = matrix_method(A, b)
print("Решение матричным методом:")
print("Первый проект:", x_matrix[0], "рублей")
print("Второй проект:", x_matrix[1], "рублей")
print("Третий проект:", x_matrix[2], "рублей")
print("-" * 30)


Решение с помощью np.linalg.solve:
Первый проект: 400000.0 рублей
Второй проект: 200000.0 рублей
Третий проект: 400000.00000000006 рублей
------------------------------
Решение методом Крамера:
Первый проект: 399999.99999999953 рублей
Второй проект: 200000.0000000001 рублей
Третий проект: 399999.99999999953 рублей
------------------------------
Решение матричным методом:
Первый проект: 400000.0 рублей
Второй проект: 200000.0 рублей
Третий проект: 400000.0 рублей
------------------------------
